"""migrations

Revision ID: 65db0784a6dc
Revises: c3b78b5a6ebf
Create Date: 2025-01-15 22:11:50.211092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65db0784a6dc'
down_revision: Union[str, None] = 'c3b78b5a6ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('model_type', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('count', sa.Integer(), nullable=False))
    op.drop_column('purchases', 'model')
    op.drop_column('purchases', 'payment_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('purchases', 'count')
    op.drop_column('purchases', 'model_type')
    # ### end Alembic commands ###
