"""migrations

Revision ID: 8d88ed936f63
Revises: 3f2b2ea7fef2
Create Date: 2025-01-15 12:40:54.448773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d88ed936f63'
down_revision: Union[str, None] = '3f2b2ea7fef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychotypes', sa.Column('chat_model', sa.Enum('GPT_4O', 'GPT_4O_MINI', name='chatmodelenum'), nullable=True))
    op.drop_column('psychotypes', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychotypes', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('psychotypes', 'chat_model')
    # ### end Alembic commands ###
