"""migratoins

Revision ID: 94c5b91e8132
Revises: c7d4eb476c4d
Create Date: 2025-01-16 15:00:41.444328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c5b91e8132'
down_revision: Union[str, None] = 'c7d4eb476c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channel_id')
    # ### end Alembic commands ###
