"""migrations

Revision ID: c354e4fddfa8
Revises: 8d88ed936f63
Create Date: 2025-01-15 13:21:01.142732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c354e4fddfa8'
down_revision: Union[str, None] = '8d88ed936f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'order_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
