"""migrations

Revision ID: c3b78b5a6ebf
Revises: 602243bdf084
Create Date: 2025-01-15 17:59:12.786913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b78b5a6ebf'
down_revision: Union[str, None] = '602243bdf084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_text_limits_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('free_image_limits_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_image_limits_count')
    op.drop_column('users', 'free_text_limits_count')
    # ### end Alembic commands ###
